# Generated by Django 4.1.1 on 2022-09-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('postdate', models.DateTimeField(verbose_name='posted on')),
            ],
        ),
    ]
