# Generated by Django 4.1.1 on 2022-10-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=200)),
                ('postdate', models.DateTimeField(verbose_name='posted on')),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
